chat/main.cpp

[feat] github test

---

chat/main.cpp

[feat] headline test2

---

chat/main.cpp

[feat] github test3

---

signIn-login/DBmodule.hpp
signIn-login/main.cpp
signIn-login/signIn-login.vcxproj
signIn-login/signIn-login.vcxproj.filters
signIn-login/signinClass.hpp

C++서버에서 쿼리 요청보내서 MySQL db의 데이터 조회

[feat] 쿼리 요청 테스트

---

signIn-login/json.hpp
signIn-login/main.cpp
signIn-login/signinClass.hpp

/signin api호출하면 json형식으로 입력한 값 db에 삽입되는 것 확인

[feat] SignIn

---

chat/DB.hpp
chat/chat.sln
chat/chat.vcxproj
chat/chat.vcxproj.filters
chat/chat_send.hpp
chat/httplib.h
chat/main.cpp

mysql/jdbc.h 파일 include 안되는 것 수정

[fix] chat_solution

---

signIn-login/main.cpp
signIn-login/signinClass.hpp

[feat] jwt auth apply

---

chat-admin/chat_ban.hpp
chat-admin/json.hpp
chat-admin/main.cpp

[fix] ban_02

---

signIn-login/main.cpp
signIn-login/signinClass.hpp

계정 삭제 시 user_status 2로 변경 -> admin이 승인 시 탈퇴 처리

[feat] accout deletion

---

api-gateway/main.cpp
signIn-login/main.cpp

[fix] CORS 설정

---

chat/DB.hpp
chat/chat_send.hpp
chat/json.hpp
chat/main.cpp

클라이언트에서 보내온 json 타입의 데이터 값을 받아오게 수정

[fix] chat_send

---

api-gateway/main.cpp
signIn-login/signinClass.hpp

[feat] signup

---

api-gateway/main.cpp
signIn-login/main.cpp
signIn-login/signinClass.hpp

[feat] validation check

---

chat-admin/admin_select_delete.hpp
chat-admin/chat-admin.vcxproj
chat-admin/chat-admin.vcxproj.filters
chat-admin/exception.h
chat-admin/httplib.h
chat-admin/main.cpp
chat-admin/prepared_statement.h
chat-admin/resultset.h

[feat] 조회, 삭제

---

chat/chat_send.hpp
chat/main.cpp

[fix] chat_insert

---

chat-admin/chat_ban.hpp
chat-admin/main.cpp

[fix] chat_ban_fix

---

chat-admin/admin_select_delete.hpp
chat-admin/main.cpp

[feat]select

---

chat-admin/main.cpp

[feat]message_delete

---

chat/chat.vcxproj
chat/chat.vcxproj.filters
chat/main.cpp
chat/test.hpp

[feat]chat_select

---

chat-admin/DB_admin.hpp
chat-admin/admin_select_delete.hpp
chat-admin/main.cpp

[fix]annotation

---

chat-admin/admin_select_delete.hpp
chat-admin/chat-admin.vcxproj
chat-admin/main.cpp
chat/chat.vcxproj

[feat]admin_status

---

chat-admin/change_pw.hpp
chat-admin/chat-admin.vcxproj
chat-admin/chat-admin.vcxproj.filters
chat-admin/main.cpp

[feature] change_PW

---

chat-admin/admin_select_delete.hpp

[fix]user_id추가

---

chat/chat_room.hpp

Redis의 Publisher와 Subscribe 기능을 이용한 채팅방 개설

[feat] chat_room

---

chat/DB.hpp
chat/chat.vcxproj
chat/chat.vcxproj.filters
chat/chat_room.hpp
chat/chat_send.hpp
chat/main.cpp

[fix] chat_room

---

chat/chat_print.hpp

[fix]chat_print

---

chat-admin/admin_select_delete.hpp
chat-admin/change_pw.hpp
chat-admin/main.cpp

비밀번호 변경 시 현재 비밀번호와 DB 비밀번호가 동일한지 확인 기능 추가

[fix] add compare DB

---

signIn-login/DBmodule.hpp
signIn-login/main.cpp
signIn-login/signinClass.hpp

delete 중복 실행되는것 방지하기 위해 스마트 포인터에서 일반 포인터로 변경

[fix] conn 타입 변경
